black_dim = "#261615"
black = "#2b1b1a"
black_bright = "#312120"

red_dim = "#994545"
red = "#bf5858"
red_bright = "#cb7270"

pink_dim = "#875795"
pink = "#a86eba"
pink_bright = "#b584c5"

green_dim = "#638261"
green = "#7ca37a"
green_bright = "#8fb08d"

yellow_dim = "#85752b"
yellow = "#a69238"
yellow_bright = "#b3a25a"

orange_dim = "#74483b"
orange = "#bd7964"
orange_bright = "#bd7964"

blue_dim = "#3e6794"
blue = "#4f81b8"
blue_bright = "#6994c3"

purple_dim = "#6e5a9d"
purple = "#8a72c4"
purple_bright = "#9a87ce"

cyan_dim = "#52826d"
cyan = "#649b82"
cyan_bright = "#7fb19a"

white_dim = "#b09e99"
white = "#edd6cf"
white_bright = "#f4e6e2"

gray_dim = "#494343"
gray = "#4e4747"
gray_bright = "#544d4d"

accent_dim = "#9d6b5b"
accent = "#c48673"
accent_bright = "#ce9887"

background_h = "#251211"
background_0 = "#2b1817"
background_1 = "#332120"
background_2 = "#3d2b2a"
background_3 = "#473534"
background_4 = "#51413e"
background_5 = "#5b4b4a"

foreground_h = "#f8f7f7"
foreground_0 = "#e3e0e0"
foreground_1 = "#cec9c9"
foreground_2 = "#bab3b2"
foreground_3 = "#a69d9c"
foreground_4 = "#938787"
